# Generated by Django 3.2.4 on 2021-06-27 12:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0009_auto_20210627_1040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
                ('objects_volvo', django.db.models.manager.Manager()),
            ],
        ),
    ]
