# Generated by Django 3.2.4 on 2021-06-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0010_alter_auto_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
            ],
        ),
    ]
