# Generated by Django 3.2.4 on 2021-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0012_alter_auto_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(related_name='cars', to='motorpool.Option'),
        ),
    ]
