# Generated by Django 3.2.4 on 2021-07-08 17:24

from django.db import migrations, models
import motorpool.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0018_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=motorpool.models.get_upload_to_auto),
        ),
    ]
